[package]
name = "shim-3ds"
authors = [ "Rust3DS Org", "Andrea Ciliberti <meziu210@icloud.com>" ]
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
ctru-sys = { git = "https://github.com/Tom60-rust3ds/ctru-rs" }
libc = "0.2.139"
